### PR TITLE
Skip verify to master

### PR DESCRIPTION
**Pull request by frankwg**
https://github.com/open-cluster-management/multicloud-operators-subscription/pull/247 is difficult to merge.
Instead, I ported the logic to the master branch directly.

### CODE REVIEW

**Comment by frankwg** [comment]
Got the  error in the travis log:

+make lint

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                 Dload  Upload   Total   Spent    Left  Speed

100    93  100    93    0     0    478      0 --:--:-- --:--:-- --:--:--   479

.build-harness-bootstrap:1: *** missing separator.  Stop.

**Comment by ianzhang366** [comment]
Hi @frankwg 

Yup that issue on travis is still due to your travis settings, there isn't that much we can change at the moment.

Anyway, I want to merge your commit as soon as possible though, do you have time for a meeting we can go through some possible solutions for your commits.

Please do let me know your time perference.

**Comment by frankwg** [comment]
I‘m available any time except 5pm ~ 9pm Beijing time everyday.

**Comment by ianzhang366** [comment]
@frankwg can we do it today 9.40am Beijing Time?

**Comment by frankwg** [comment]
sure, but how?  webex?

**Comment by ianzhang366** [comment]
https://bluejeans.com/146574401

**Comment by ianzhang366** [comment]
PR is in the ibm branch, close for now

**Pull request closed without merging**
