### PR TITLE
upgrade CRD version to v1, also keep the v1beta1 version for managed …

### PR DESCRIPTION
**Pull request by xiangjingli**
…cluster usage

Signed-off-by: Xiangjing Li <xiangli@redhat.com>

https://github.com/open-cluster-management/backlog/issues/10642

The PR is to refresh app CRDs to v1, including:

1. apps.subscription CRD need to provide two versions - v1 used in ACM Hub.  V1 and V1beta1 are required in managed cluster. Helm chart will decide which version to be installed in managed cluster.
2.  refresh all other CRDs to v1, which are used in unit test and demo usage. 
3.  other fixes that caused the failure of unit test.

### CODE REVIEW

**Comment by xiangjingli** [comment]
@mikeshng @rokej Please hold the PR, Just found the deployable V1 CRD have some other issues, that caused the failure of the unit test in deployable repo, though the unit test in application repo has passed. I will come up with new fix tomorrow.

**Comment by mikeshng** [comment]
reopening in another PR because hung sonar scan

**Comment by mikeshng** [comment]
reopening to see if hung prow jobs are fixed.

**Pull request merged**
