### PR TITLE
Continuously reconcile differences in cluster resources with repo

### PR DESCRIPTION
**Pull request by rokej**
Git repo subscription used to reconcile a resource only when the commit ID of the subscribed repo is changed and the resource has changed in the repo. Once the resource is applied to cluster, any manual changes to the resource are not reconciled until those conditions are met. This PR is to change the behaviour of the subscription so that it continuously reconciles cluster resources to the repository's resources. The repository is the single source of truth.

### CODE REVIEW

**Comment by ianzhang366** [comment]
Hi, @rokej do you mean after the git resource is deployed to the cluster, then the user's modification of the resource will be overridden based on the git.

In other words, if a user wants to change the end result of a git subscription, the only way(or the correct way) should be changed and commit to the git repo. 

Am I understand the flow correctly?

**Comment by rokej** [comment]
@ianzhang366 Yes, that's correct.

**Comment by ianzhang366** [comment]
Hi @rokej , the code look good to me.

Only 1 minor suggestion, I'm seeing you are passing in `commitID`, but within the function, we are not using the `commitID`. I guess you wanted to use the `commitID` to skip unnecessary download, am I right? If that's the case, can we utilize this `commitID` parameter?

`func (ghsi *SubscriberItem) cloneGitRepo() (commitID string, err error) {`

**Comment by rokej** [comment]
@ianzhang366 That's a very good observation. However, we store git-commit in subscription annotation too. Instead of removing it, I added a line of code to log commit ID so enough information is available for troubleshooting.

**Pull request merged**
