### PR TITLE
Add insecure-skip-verify support to git clone

### PR DESCRIPTION
**Pull request by frankwg**
https://github.com/open-cluster-management/multicloud-operators-subscription/issues/239

### CODE REVIEW

**Comment by ianzhang366** [comment]
@frankwg the change looks good to me.

Can you please add some comments in your code to trigger the Travis build?

**Comment by frankwg** [comment]
@ianzhang366 I added a comment to code, but travis is still not starting the build.

**Comment by ianzhang366** [comment]
Hi @frankwg  I will have to check up with our CIDC team and get back to you

**Comment by ianzhang366** [comment]
Hi @frankwg it seems our current CIDC process is not that efficient to handle Forked PR. 

I will force this merge and PR it to the master

**Pull request merged**
